modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="izi_pistols"
version="1.0.0"
displayName="IZI PISTOLS"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Matthieu, MCreator"

[[dependencies.izi_pistols]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




